###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
####consul注册中心地址
  cloud:
    consul:
      host: 192.168.5.128
      port: 8500
      discovery:
        # 程序部署地址IP
        hostname: 192.168.1.173
        service-name: ${spring.application.name}





